# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 968754f012c82b2c28631bcf6d8b4ee18bdb16319705ea99ab0fbab3ea103979fa2ee80e704b0c654bfb23ae2700631f470ccfe112f934c146c9a6b527bb252a

test:
  secret_key_base: f94a73502c08e8ab0cd005c04a2e7fea5dc07c00bdc8c742043489ad6c369369b798d6434ce239f6dcb85374836bbdc6e49d8af51a79155298a54bed916d49af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
